### ISSUE TITLE
license

### ISSUE THREAD

**Issue by seru71** [MonashBioinformaticsPlatform/bio-ansible#24]
Hi,

Thank you for developing and publishing this project. I found your playbook very useful and would like to modify & use it to set up a local bioinfo server. Have you chosen a license under which the code is released?

**Comment by pansapiens** [comment]
Hi  @seru71 - it's great that you are finding it useful. After some brief discussion around the office we decided on Apache 2.0. Feel free to lodge further issues / pull requests if you hit any bugs or add any useful tasks.
