### ISSUE TITLE
ansible-2.10 branch

### ISSUE THREAD

**Issue by serine** [MonashBioinformaticsPlatform/bio-ansible#31]
I've made some improvement to bioansible, mostly cosmetic/minor to make sure it plays nicely with  latest ansible. The main problem with existing bioansible is `include_task` statement through out the book, mainly under `roles/bio_tools`. 

I started fixing this, but haven't pushed to github yet, as I haven't finished.

**Comment by pansapiens** [comment]
Closed with e15679d
